students home work. I try the best))
Oleksii1985/Voitiuk_front_end_26102022 pull request #26
Opened 2023-01-28 14:26 UTC by Oleksii1985

2023-01-29 08:03 UTC, kosachevlad requested changes

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +  }
wrong implementation of method setFullName. After this method is called, the user's name and surname should change!

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +console.log(alex.setFullName("Oleksii Voitiuk"));
You probably didn't understand the setFullName method right away. Let me explain: it's supposed to reassign the user's first and last name to the given instance. You can test it this way :
```javascript
console.log(alex.getFullName()); // 'Oleksii Voitiuk'
alex.setFullName("John Doe");
console.log(alex.name) // 'John'
console.log(alex.surname) // 'Doe'
```

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +    };
marks shouldn't be inside info object.
your constructor should like :
```javascript
constructor(info) {
  super(info);
  this.marks = info.marks;
}
```
and refer to the marks value below the code like this  `this.marks`

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +      this.info.marks.reduce(
`this.marks.reduce(`

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +      ) / this.info.marks.length
`this.marks.length`

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +    return Math.min.apply(Math, this.info.marks);
1.  `return Math.min.apply(Math, this.marks);`

2. let me show shortened code with rest operator ``` return Math.min(...this.marks);```

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +    return Math.max.apply(Math, this.info.marks);
same...

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +      marks: this.#cheatedMarks,
same mistake as in Student constructor..

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +  }
wrong implementation. Group must be specified in the constructor when creating the teacher instance 
`let John = new Teacher({name: 'John', surname: 'Doe', age: 30, group: [vlad, den, marta, sveta, ben, nik]})`
and your constructor should look like :
```javascript
constructor(info) {
    super(info);

    this.group = info.group
  }
  ```

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +  }
and change this.group.studentsList to this.group everywhere below the code

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +console.log(teacher.updateStudentByName(eva, "Marta"));
Actually not bad.

2023-01-29 08:03 UTC, kosachevlad commented on lesson_20_1/students.js
> +});
wrong instance creating...

2023-01-30 18:03 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +  }
Done

2023-01-30 18:04 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +console.log(alex.setFullName("Oleksii Voitiuk"));
already fixed

2023-01-30 18:07 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +    };
done

2023-01-30 18:08 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +      this.info.marks.reduce(
done

2023-01-30 18:08 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +      ) / this.info.marks.length
done

2023-01-30 18:09 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +    return Math.min.apply(Math, this.info.marks);
ok

2023-01-30 18:10 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +    return Math.max.apply(Math, this.info.marks);
ok

2023-01-30 18:10 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +      marks: this.#cheatedMarks,
+

2023-01-30 18:23 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +  }
done

2023-01-30 18:24 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +console.log(teacher.updateStudentByName(eva, "Marta"));
ok

2023-01-30 18:24 UTC, Oleksii1985 commented on lesson_20_1/students.js
> +});
changed

2023-02-01 19:42 UTC, kosachevlad approved these changes

2023-02-01 19:42 UTC, kosachevlad commented on lesson_20_1/students.js
> +    this.info = {
why do you need info?

2023-02-01 19:42 UTC, kosachevlad commented on lesson_20_1/students.js
> +    return `${this.info.name} ${this.info.surname}`;
return `${this.name} ${this.surname}`;

2023-02-01 19:42 UTC, kosachevlad commented on lesson_20_1/students.js
> +    this.info.surname = fullNameArray[1];
this.name = fullNameArray[0];
    this.surname = fullNameArray[1];

2023-02-01 19:42 UTC, kosachevlad commented on lesson_20_1/students.js
> +  }
```javascript
 constructor({name, surname, age, marks}) {
   super({name, surname, age});
   this.marks = marks;
   }
   ```

2023-02-01 19:42 UTC, kosachevlad commented on lesson_20_1/students.js
> +  }
Well if you wanna find just one student its better to use array.find

2023-02-03 11:53 UTC, merged